### ISSUE TITLE
Builder uses Collections unmodifiable on collections ... as option or even on by default

### ISSUE THREAD

**Issue by rbygrave** [avaje/avaje-record-builder#16]
I'm thinking that "by default" collection types should be wrapped via e.g. Collections.unmodifiableList() and the like at build time.

The thinking is that a "record graph" should be as unmodifiable as possible. I'm actually thinking this should be the default with perhaps the option to turn it off.

**Comment by SentryMan** [comment]
I don't know about this one

**Comment by SentryMan** [comment]
it's been two months, if anybody else requests we can circle back I think.
