### ISSUE TITLE
Propagate TYPE_USE annotations

### ISSUE THREAD

**Issue by agentgt** [avaje/avaje-record-builder#19]
@SentryMan I'm not sure if you stumbled on my [rant with the original record builder author](https://github.com/Randgalt/record-builder/issues/111) on the need to propagate `TYPE_USE` annotations but I recommend you do that.

The basic problem is you cannot not just toString on the TypeMirror to get the correct representation. I believe @bowbahdoe ([who has a similar library](https://github.com/bowbahdoe/magic-bean)) filed a JDK bug on it.

Luckily I have a solution you can just copy from JStachio: https://github.com/jstachio/jstachio/blob/main/compiler/apt/src/main/java/io/jstach/apt/internal/util/ToStringTypeVisitor.java

The top static method is what you want to call. Yes that class is internal so doc sucks.

So just for clarity:

```java
@GenerateBuilder // or whatever the annotation is
record Blah(@Nullable String foo){}
```

Let us assume we are using JSpecify.

When you produce all the setters for the builder it should be:

```java
public Builder foo(java.lang. @org.jspecify.annotations.Nullable String) {
...
}
```

If you call `ToStringTypeVistor.toCodeSafeString(someTypeMirrorFromRecordAccessor)`

BTW the above is one reason I do not manage imports on code generation (e.g. FQN everything). It is nontrivial to recreate the correct TYPE_USE annotation declaration and is probably why even the JDK has a bug.

You will have to modify my code heavily if you plan on managing imports.

If I have time later this week I can put in a PR for you.

On another tangent I think I remember you or @rbygrave using Eclipse or perhaps the compiler. I have a great deal of the annotation processing API as well as the JDK API nullness annotated aka Eclipse External Annotations aka EEA. You just copy this directory: https://github.com/jstachio/jstachio/tree/main/etc/eea

Then just copy the checkerframework, errorprone (optional), and eclipse profiles from this pom:
https://github.com/jstachio/jstachio/blob/main/api/jstachio/pom.xml

You will probably have to twiddle some config but that will get you headless null analysis and the Eclipse version is mostly equivalent to Checker (IMO better than Checker because Checker just assumes the entire JDK is nonnull where as eclipse is the opposite).

**Comment by SentryMan** [comment]
Hey that's pretty good, thanks.

**Comment by bowbahdoe** [comment]
That toString should be fixed as of 20

**Comment by bowbahdoe** [comment]
https://bugs.openjdk.org/browse/JDK-8281238?jql=text%20~%20%22type%20use%20toString%22

**Comment by SentryMan** [comment]
> The basic problem is you cannot not just toString on the TypeMirror to get the correct representation. I believe @bowbahdoe ([who has a similar library](https://github.com/bowbahdoe/magic-bean)) filed a JDK bug on it.

oh yeah this thing, I usually [use regex to deal with it](https://github.com/avaje/avaje-validator/blob/1159732d2dda42ade616a71e000105430e05a768/validator-generator/src/main/java/io/avaje/validation/generator/Util.java#L93-L107) to extract

**Comment by SentryMan** [comment]
so in the case of 
```
@RecordBuilder
public record TypeUse(@NotEmpty Map<@Nullable String, @NotBlank  Map<@NotBlank String, @Nullable List<@Nullable String>> map) {}
```
does it matter if the nested map has the annotations copied? or do only the top level (`@Nullable String, @NotBlank  Map`) ones need to be copied to the setter?

**Comment by agentgt** [comment]
> does it matter if the nested map has the annotations copied?

Yes it matters. Its like removing the generics if you do... speaking of which the regex to remove annotations there is a way to erase them without doing that as well.

After labor day I can look into contributing to help.

**Comment by SentryMan** [comment]
this visitor thing is actually legendary, I didn't know you could do this. You really learn something new every day.

**Comment by SentryMan** [comment]
managed to get the annotation copying close to how I wanted, but apparently this signature is invalid:
```java
   TypeUseBuilder  map(
      @NotEmpty @NotBlank
          Map<
                  @NotBlank String,
                  @NotEmpty List<@NotBlank Raven.Weapon>>// <-- this notblank is invalid
              map) {...
```
So I'm forced to use fqn no matter what after a certain point.

**Comment by agentgt** [comment]
That visitor actually was not my finest moment. I embarrassingly reverted to using System.out debugging when making it because the recursive nature was confusing with a real debugger. I don't normally do that and meant to take those out.

**Comment by SentryMan** [comment]
in any case, are the setter changes to your liking?

**Comment by agentgt** [comment]
I think so. I will pull/fork later and try.
