### ISSUE TITLE
Very cool ... should there be any Javadoc?

### ISSUE THREAD

**Issue by rbygrave** [avaje/avaje-record-builder#2]
My preference is to actually **_NOT_** have Javadoc in the generated class.

That sounds a bit weird I know, my thinking is that the builder pattern is _SOOO_ predictable that the Javadoc does not actually add anything or help the person reading the code.  In the _"less is more"_ thinking it is actually better to not have the Javadoc at all.

**Comment by SentryMan** [comment]
You know, this, I know this, but the maven javadoc plugin doesn't know this.
